name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build and Test Job
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Blake CLI
        run: dotnet tool install -g Blake.CLI

      - name: Bake static content
        run: blake bake
        working-directory: src

      - name: Build the site
        run: dotnet build src/BlakeSampleDocs.csproj --configuration Release

      - name: Test build output
        run: |
          if [ ! -d "src/.generated" ]; then
            echo "Error: Blake generated content not found"
            exit 1
          fi
          echo "✅ Build completed successfully"
